### ISSUE TITLE
[Request New Content] Why fast and effective data labelling is a competitive advantage

### ISSUE THREAD

**Issue by theodu** [kili-technology/kili-blogger-program#11]
### Community vote
👍 Upvote if you like this topic
🚀 If you can make the article/video!

Thank you.

**Comment by choutkamartin** [comment]
I would take this but I think the title is a bit misleading. Fast and effective data labelling was always a competitive advantage. So, I think the article should be renamed to "Why fast and effective data labelling is a competitive advantage".

**Comment by theodu** [comment]
hi @choutkamartin,
I agree with you, thank for the comment, I change that.
If you are interested to write this article, please provide a detailed outline of what you have in mind.

Merry Christams !

**Comment by Yukti-09** [comment]
Hey! Merry Christmas!

I'm interested to take this up!

I have hereby attached an outline of how I wish to write the article.

**Outline:**

1. Faster iterations
2. More accuracy 
3. An error could lead to catastrophic failures
4. Identify borderline cases
5. Better decision making

**Comment by choutkamartin** [comment]
Hey,

I wish you all the best in the new year. I wrote a little detailed outline. Hopefully, it will make sense, as I'm writing this very late. I will, of course, improve the content if I will get the article.

Thank you, have a great day!

**To my detailed outline:**

1. Why data labelling?
2. Labelling takes away too much time
3. Time is money, so is efficiency
4. Why is accuracy crucial
5. Why are data labelling platforms such as Kili important

### Why data labelling?
Data labelling has been on an uptrend since 2014, and there's no way why it shouldn't be. We need data labelling in lots of aspects of today's life. There are several industries where machine learning is on an uptrend:

- Automotive
- Retail
- Army
- Banking
- Healthcare
- Manufacturing

In automotive, we need data to enhance models used in autonomous cars. In manufacturing, AI is used to detect defective products, making the entire process cheaper and more efficient.

### Labelling takes away too much time.
Most companies don't have the necessary resources to label their data accurately and effectively. If they do label, it takes them way too much time. And time could be split into other parts of machine learning - such as tuning the machine learning model.

### Time is money, so is efficiency.
As we all know, time is money. As we described before, labelling takes way too much time. In the hands of a specialized company like Kili, you can forget about the whole data labelling part. Focus instead on the more important topic, such as the machine learning model itself.  

### Why is accuracy crucial.
When we need to have our machine learning model accurate, we need to feed it with the most accurate data. Nowadays, data labelling isn't only about drawing boxes over specific objects. It's about polygons, multiple classes, human insight - in some ways, we could say, it's about perfection. The more data you gather, the better model you will get. The more variant data your model will get, the better it will understand things in the future.

### Why are data labelling platforms such as Kili important
Data labelling platforms are essential, as they can deliver the best results in the least time. Not only can Kili help you with annotating images, but its platform also supports annotating text, video and speech. These types of annotations need an unbiased view from qualified people.

**Comment by theodu** [comment]
Hi @choutkamartin 
Thank you for this very detailed outline. And sorry for the late reply, the end-of-the-year period froze operations.
The ideas of this article are already in other articles already in writing. We gave a list of first article proposals at the beginning but this one is very close to others. In order not to duplicate content, I will have to put this one on hold.
Sorry for doing so but we have to rethink to what we expect in this article.
Best wishes

**Comment by theodu** [comment]
Due to content redundancy, I have to cancel this issue,
best,
Théo
