### ISSUE TITLE
[Request New Content] What code is to software, data is to AI

### ISSUE THREAD

**Issue by theodu** [kili-technology/kili-blogger-program#12]
### My Request

What code is to software, data is to AI.
Today code and computing power are not anymore a big issue for creating performant ML models. Data is. Improving the dataset has a bigger leverage effect than investing a lot of time on improving the model.
You can find the general idea in the talk of Edouard d'Archimbaud at World Summit AI, 2021 Amsterdam : https://www.youtube.com/watch?v=Hk5Z6nCjUmo&ab_channel=WorldSummitAI

### Community vote
👍 Upvote if you like this topic

Thank you.

**Comment by Yukti-09** [comment]
Can I please be assigned to this article?

**Comment by theodu** [comment]
Hi @Yukti-09
thank you for your interest!

According to the FAQ, in order to get assigned to an article, please provide a detailed outline of what you have in mind. 
The more it is detailed, the more we will understand how you intend to write it and the more it will increase your chance to be assigned to this article

Thank you and Merry Christmas!

**Comment by DamianArado** [comment]
Data analysis allows us to learn new things about the world and about ourselves. It can also be flawed, debunked, biased, and misused. Big Data emerged as a field referring to organizing, structuring, and analyzing complex and large data sets to manage, use and make sense of the overwhelming amount of digital data that we create. 

Data Science emerged as a field that encompasses the entire lifecycle of data--including experiencing data, making sense, and putting it to use--big or small.

Data’s implications, like with AI, change where and how we use them. It depends on the industry, the organizations, the use cases, the level of autonomy, and even the tasks. Before we get to specific ethical implications, we'll review the aspects of data and the current landscape of Data Science that makes it both exciting, challenging, and definitely complicated.

In this article, our objectives would be to: Define Data Science and discuss the impact of data, Explain the stages, challenges, and lifecycle of data, Familiarize yourself with key data governance technology and Articulate the key framework for business intelligence and ethics in data science and data-driven business: data, information, knowledge, and wisdom.

Proposed outline for the same:
- Data exists everywhere
- Why do we call it Data Science
- Challenges associated with Data Science
- The evolving nature and values of data
- Our Trust is impacted by whatever we extract, keep and use
- Lifecycle of data
- Governance of data
- Using data to make wise decisions

My proposal would be to change the topic to: "What code is to software, data is to Data Science" and I believe I can provide a nice article for the same. 

Have a great week, Merry Christmas!

**Comment by theodu** [comment]
Hi @DamianArado 
This does not correspond exactly to what I had in mind. Sorry, not to have precise it on the description. 
the idea would be to have an article that deals with the same ideas as the ones addressed by Edouard d'Archimbaud in his talk at Wold Summit AI, 2021. I update the description and add a link to this talk.

**Comment by Renerd-max** [comment]
Hi, @theodu I think I got the idea, here is my outline:

**Introduction:** Information is empowered by the advent of software engineering, which comprises the web, and native app and software. A boost in information technology can be described as the advent of AI, we can make our software and computer hardware, such as robots performs an intelligent task that is otherwise reserved for human.

AI exists on the foundation of software engineering, and they are intertwined, but while we need codes to make software what it is, we equally need data to build an AI model, our AI cannot be successful without the availability of high-quality data, likewise, our software cannot be successful without effective and quality code inputs.

AI model is highly sensitive to data input that a small change in accuracy will result in a considerable degree of inefficiency in our AI, thus, the importance of sourcing high-quality data to train AI, equally, if our code is inaccurate, we can not produce an effective software.

But while we have conventions in coding and the software industry has developed to a stage whereby software can be produced within a very short period, using practices, such as CI/CD. AI is a relatively new field and as such faced with the challenge of mining and sorting data, which can impact not only the quality of the code, but the time taken for the model to reach production.

This challenge can be divided into two, including Having consistent data and Having Comprehensive data.

At Kili, we tackle these challenges to help you build quality AI and improve the time taken to bring your model into production, we shall look at these challenges and how we tackle them at Kili.

**Sub-Head 1: The Challenge of Having Consistent Data**

Talks about how inconsistent data can impact the quality of the model in training, and how kili helps solve this by integrating Consensus, and instructions.

**Sub-Head 2: The Challenge of Having Comprehensive Data**

Talks about the importance of having data that can address every aspect of which the model will be used, this can be challenging, but we can solve this using a different approach in Kili, we can Slice the data, iterate fast to see the result of the output and make quick decisions, and updating the data after production.

All the solutions will be listed as a sub-point.

**Conclusion**

**Comment by theodu** [comment]
Hi @Renerd-max 
Thank you for your outline. This topic is very close to the one of issue #13. In order to refine it and avoid redundancy, we will not propose these two articles at the same time, I put it On Hold.
thanks!

**Comment by theodu** [comment]
I cancel this issue because of redundancy
