### ISSUE TITLE
[Article Proposal] Tutorial: Building a Neural Network From Scratch in NumPy

### ISSUE THREAD

**Issue by Graeme22** [kili-technology/kili-blogger-program#30]
### My resource

**Topic:**
Building a Neural Network From Scratch in NumPy

**Outline:**
This article would be math-heavy. The goal would be to explain how deep learning works at a mathematical level, using linear algebra and calculus. Once that is established, I would demonstrate how to create a basic feed-forward neural network using only `numpy`, and then train it on the MNIST dataset to see how well it performs. Understanding the mathematical basis behind deep learning allows us to understand it more deeply, facilitating better research and comprehension in the future.

### My content is

- [x] A Kili Tutorial / Guide / How to article
- [ ] An Article

**Comment by TanyaChutani** [comment]
@kili-technology I can also take this up!

**Comment by theodu** [comment]
Hello @Graeme22 @TanyaChutani 
Thank you for your interest and your article proposal.
This subject does not really fit in the Kili scope because it does not deal with dataset creation or annotation. The role of Kili Technology comes one step before the model development step. Our purpose is the Data and to help data scientists to optimize their model performances by working on the data and not on the model. Thus, We won't select this content proposal.

For your next article proposal, we ask you to write a more detailed outline, with bullet points and key ideas. It helps us to understand what you have in mind and increase your chance to get assigned to your article.

Thank you and best wishes!
