### ISSUE TITLE
[Article Proposal] Tutorial: Intro to Reinforcement Learning

### ISSUE THREAD

**Issue by Graeme22** [kili-technology/kili-blogger-program#31]
### My resource

**Topic:**
Tutorial: Intro to Reinforcement Learning

**Outline:**
This tutorial would give an introduction to reinforcement learning, starting with the mathematical basis behind it and finishing with a simple implementation using the OpenAI `gym` library. The goal is to introduce the basics of a new learning paradigm.

### My content is

- [x] A Kili Tutorial / Guide / How to article
- [ ] An Article

**Comment by theodu** [comment]
Hello @Graeme22 
Thank you for your interest and your article proposal.
This subject does not really fit in the Kili scope because it does not deal with dataset creation or annotation at all. We won't select this content proposal.

For your next article proposal, we ask you to write a more detailed outline, with bullet points and key ideas. It helps us to understand what you have in mind and increase your chance to get assigned to your article.

Thank you and best wishes!
