### ISSUE TITLE
[Article Proposal] Tutorial: Extract Individual Components from a audio file of mixed elements using Unsupervised Learning

### ISSUE THREAD

**Issue by sharmas1ddharth** [kili-technology/kili-blogger-program#32]
### My resource

**Topic:**
Tutorial: Extract Individual Components from mixed recording using Unsupervised Learning

**Outline:**
This tutorial would give an introduction to Unsupervised Machine Learning (ICA) in Python by creating a small project in which individual components will be extracted from a recording of 2 or more mixed audio elements 

### My content is

- [x] A Kili Tutorial / Guide / How to article
- [ ] An Article

**Comment by theodu** [comment]
Hello @sharmas1ddharth 
Thank you for your interest and your article proposal.
This subject does not really fit in the Kili scope because we currently don't handle such advanced audio pre-processing but only speech-to-text tasks. We won't select this content proposal.

 However, if you have other ideas for an audio use case and how Kili could help to solve this use case, we will be interested!

For your next article proposal, we ask you to write a more detailed outline, with bullet points and key ideas. It helps us to understand what you have in mind and increase your chance to get assigned to your article.

Thank you and best wishes!
