### ISSUE TITLE
[Article Proposal] Tutorial : Introduction to Feature Selection

### ISSUE THREAD

**Issue by dushyantRathore** [kili-technology/kili-blogger-program#33]
### My resource

**Topic:**
Introduction to Feature Selection using Python

**Outline:**
The tutorial would introduce the various feature selection strategies and discuss their implementation in Python. It would start with designing a particular strategy, implementing it using Scikit-learn, and analyzing the results on a sample dataset.

### My content is

- [x] A Kili Tutorial / Guide / How to article
- [ ] An Article

**Comment by theodu** [comment]
Hello @dushyantRathore Hello @dushyantRathore 
Thank you for your interest and your article proposal.
This subject does not really fit in the Kili scope because it is more model-development related rather than dataset creation related. We won't select your proposal.

For your next article proposal, we ask you to write a more detailed outline, with bullet points and key ideas. It helps us to understand what you have in mind and increase your chance to get assigned to your article.
Thank you and best wishes!
