### ISSUE TITLE
[Article Proposal] Journey and Storage of Data in production ML environment

### ISSUE THREAD

**Issue by DamianArado** [kili-technology/kili-blogger-program#50]
### My resource

**Topic:** This article demonstrates the lifecycle of data in machine learning specific production environments. We will also see how we can use machine learning metadata, how to iteratively create enterprise data schema and then integrating it efficiently into feature stores, data warehouses and data lakes.

**Outline:**
- Describe the journey of data through data lineage and provenance
- ML metadata (MLMD) and integrating the sequence of pipeline artifacts into metadata storage using the ML Metadata library
- Schema Development and Environments
- Data storage schemes used by enterprises
- Where we should store our data: comparison - Feature Stores, Data Warehouses, and Data Lakes

### My content is

- [ ] A Kili Tutorial / Guide / How to article
- [x] An Article

**Comment by theodu** [comment]
@DamianArado
I liked this topic and it could be very interesting. It would be nice to show where Kili is in this whole journey of data. to show the coordination between the data storage and Kili etc.
I put this article on hold, waiting for you to finish the other ones and to begin this one.

**Comment by DamianArado** [comment]
Please find the article attached below:

https://docs.google.com/document/d/1j3wsavCIH_b13aCT6t3mHLIG6GlZI0tl3HrtXfW8Uag/edit

**Comment by JustBrn** [comment]
Hi @DamianArado thanks! We'll take a look and get back to you :)

**Comment by theodu** [comment]
Hello @DamianArado!
I cannot access your document, I made a demand
Best
théo

**Comment by DamianArado** [comment]
> Hello @DamianArado! I cannot access your document, I made a demand Best théo

Hii @theodu 👋
I forgot to update the edit permissions for all. It should be accessible now.

**Comment by DamianArado** [comment]
> I don't want to explain why we can't accept such content. I think that the article's structure is good and I wouldn't see it split.

I agree. I have to do a revamp, shorten it a bit, and not be immature again.

**Comment by theodu** [comment]
Hi @DamianArado 
We have scanned your previous article with a plagiarism checker tool and we discovered that they are full of plagiarism. We decided not to continue with this article and any of your articles.

We have unpublished all your articles and we can't continue to work with you. You earn back all rights over your content. 
We cannot pay you for the 2 last articles that you delivered because they are illegal regarding the law.

Plagiarism is very punishable and can have very high legal repercussions. I advise you to check on the net about what consequences could plagiarism lead to and to take this as a lesson.

Regards,
Théo
