### ISSUE TITLE
[Article Proposal] How to label Text for Sentiment Analysis with Kili Technology

### ISSUE THREAD

**Issue by Renerd-max** [kili-technology/kili-blogger-program#52]
### My resource

**Topic: How to label Text for Sentiment Analysis with Kili Technology**

**Outline:**

-**Introduction:** The introduction will give an overview of sentiment analysis and how difficult it can be
- **Heading 1: What is Sentiment analysis**: a brief introduction to sentiment analysis, its uses, and how it can be analyzed using kili technology.
- **Heading 2: How to label texts for sentiment analysis - Good practices**
- **subheading 1:** Chose the Specific domain: you should carefully choose the test and training corpus, you should narrow your choice to the specific domain of interest.
- **subheading 2:** Remove unnecessary punctuation: you should remove unnecessary punctuation from your data set to enhance accuracy.
- **subheading 3:** limit the use of stop word: using too many stopwords in your corpus can result in poor performance.
- **subheading 4:** remove less frequent features: features appearing less frequently should be eliminated.
- **subheading 5:** Normalise your corpus: prevent the use of many variations for a word.
- **subheading 6**: use complex features: using complex features, such as n-grams, and part of speech tags can improve the accuracy of text analysis.
- **subheading 7:** Define and be Consistent with your rules: Define which data will be assigned to what rule and be consistent with it.
- **subheading 8:** Experiment with random labeling: you can also experiment with labeling your data randomly to see what model performs better, this can be done with kili text annotation tool.
- **Conclusion**

### My content is

- [x] A Kili Tutorial / Guide / How to article
- [] An Article

**Comment by theodu** [comment]
Hi @Renerd-max 
I liked this, it would make good content. However, I rather see it as a tutorial, more hands-on and showing step by step. Do you think that you could do it?
best

**Comment by Renerd-max** [comment]
@theodu I surely can make it a hands-on tutorial, I shall describe each step as a guide, I should modify the label and title

**Comment by theodu** [comment]
@Renerd-max Good, I assign you to the article, you can begin to work on it!

**Comment by Renerd-max** [comment]
Hi, @theodu here is the link to the first draft.

https://docs.google.com/document/d/1R5-TYkAHNDn5Aoclrz9ChUNU9fo16YQJ-zQ_dln863o/edit?usp=drivesdk

**Comment by theodu** [comment]
Thank you @Renerd-max.
I put a lot of comments. The main points are:
- It should be a python tutorial, not an article, you should guide the user, show more pieces of code, what package to use, etc. I am not sure that you did the whole workflow at home, you only show how to do steps independently. Do as if you were a user wanting to label text for sentiment analysis with Kili: take a corpus, upload data on Kili, label a sample, preprocess it, etc. Then the tutorial is about resituating it to the reader. 
Yes, it is more time-consuming than articles and that is why we pay a higher price for articles.
- The article lacks structure. Define steps and nested steps.

**Comment by theodu** [comment]
I changed the title so it sounds more like a tutorial. Sorry not to have spotted it before.
You should consider spending a bit more time on your content writing. It is often sloppy work.

**Comment by Renerd-max** [comment]
Thanks @theodu gone through your comments, I shall made necessary adjustments

**Comment by Renerd-max** [comment]
Hi, @theodu this has now been resolved, you may go through it again.

**Comment by theodu** [comment]
Hi @Renerd-max 
Thank you! I will have a look asap ;)

**Comment by theodu** [comment]
the content now has more the shape of a tutorial. Thank you for having taken the comment quickly.
However, every piece of code and example is taken from the same Github Repository. Even if you provide the link each time to this GitHub, that is a lot for "original content". Can you please take this back?
And also it is nice that you really advertise Kili a lot in your article but the last part is a demo of Kili. that is not the purpose.

**Comment by Renerd-max** [comment]
I can write my own pieces of code to demonstrate each step, as I did in some of the codes, but according to the guideline, we should provide a link to a GitHub repository on which the code is hosted, that was why I use that.

If it is not against the practice of this program, j should use my code for every tutorial I create.

Is this ok?

**Comment by theodu** [comment]
@Renerd-max Yes, you should write your own piece of code and host it on your own GitHub repository.

**Comment by theodu** [comment]
@Renerd-max You know what, let's say that it wasn't clear enough in the writing guidelines and let the code from the GitHub that you found. 
however, you still need to correct the last Kili demo part please

**Comment by Renerd-max** [comment]
I shall do that, I schedule it for tomorrow

Renerd

**Comment by Renerd-max** [comment]
@theodu this topic has been updated and you can now review it.

**Comment by theodu** [comment]
HI @Renerd-max,
Edouard did comments on your article. here is more detailed feedback based on them:
- All code taken from the Github page that you put doesn't bring any added value. While finding it bad, I accepted to keep it in order not to take too much time. But Edouard also spots it as adding no value whereas it is the core of your article.
- Your first draft didn't have any python code whereas it was a tutorial. You took that point but it is in fact still not enough. Your article is still composed of independent parts that don't play together. In a tutorial, when you get rid of all the text, you should be able to run all code from end-to-end, just like a Jupyter notebook. The code that you use doesn't let someone reproduce your results, because, in fact, you have no results.   
- you are very fast at writing your articles and you take feedback very quickly. That is a good point. But you take it too fast, you don't take time to write a good tutorial and to produce good and impactful content. You always rush to write good-looking content but don't invest time in writing good quality one. We might not take other articles/tutorials from you.
- The code that you copied pasted is not state of the art anymore. NLTK is outdated and not used anymore. You should use state-of-the-art libraries that people would use in business. see the example here: https://paperswithcode.com/task/sentiment-analysis. This lets me wonder if you really have experience in NLP because you also seem to be up to writing on every topic of the program. If not, it might take you a big amount of time to get up-to-date and write a proper tutorial. Otherwise, it will just be a waste of time for both of us. I let you tell me if you want to continue on this article but I doubt that it is a good idea

**Comment by Renerd-max** [comment]
Hi, @theodu like I stated earlier, I was confused by the GitHub source code.

I shall now write my code and I believe it should be more structured by then.
I agree that rushing to complete the work doesn't allow me to make good content, I have also noticed that the imported codes aren't effective, but I follow your instructions.

Don't worry, I know what I am doing and my final submission should address the issues.

Another thing to note is that my initial proposal wasn't about using kili technology, it was your suggestion to use kili and made this a tutorial, I just learn how I can effectively do that from the IDE and I shall update it with the relevant information.


Also, I am not yet advanced in this profession, I am self-taught and I am learning because I love the profession, I know NLTK and it is new to me that it is outdated, I am grateful for the corrections because they allow me to learn new information.

The whole idea is new to me, and having no previous professional experiences relating to dealing with assignments, this error occurs, but I learn from this, when next I propose a new content (I had a practical knowledge of the contents I proposed) I shall ask questions to be sure whenever you made a suggestion, I made mistakes here because it wasn't what I originally planned to write and I do not ask questions for clarification.

**Comment by theodu** [comment]
Hi Renerd,
Happy to hear it. This also makes us learn, we should maybe ask for a more detailed outline before assigning someone. Sorry to have been rough, the thing is that as we give remuneration for the blog, we suppose that you are an expert in what you write. I understand that you are learning by yourself, that is an excellent thing and I support you in this but we are looking for state-of-the-art content because the tutorial should help the professionals that want to use Kili. 
To learn by writing, this blog might not be the good one because we might be demanding and suppose that you have knowledge of state-of-the-art methods and packages.
Let's anyway try to make this tutorial! just take time to produce a good tutorial and put yourself as if you were a customer wanting to build a dataset for sentiment analysis. Don't necessarily do the demo of Kili but show your code. And as Edouard said, try to choose a more business-related subject, the tutorial target people that might want to use Kili in their company for sentiment analysis.
Maybe think of a very detailed outline and send it to me so we can build it in an iterative way ;)

**Comment by Renerd-max** [comment]
Hi @theodu, I updated this article, you can take a look
