### ISSUE TITLE
[Request New Content] Things that can go wrong while labeling data and how to avoid them

### ISSUE THREAD

**Issue by theodu** [kili-technology/kili-blogger-program#9]
### Community vote
👍 Upvote if you like this topic
🚀 If you can make the article/video!

Thank you.

**Comment by rajarshi1** [comment]
Hey, I would like to give this a shot!

**Comment by theodu** [comment]
Hi @rajarshi1 ,
Happy to hear that you are interested!
Please provide a detailed outline of what you would like to write

**Comment by Renerd-max** [comment]
**Introduction:** Unlike traditional software development where your code quality determines the output of a program, in data analysis and artificial intelligence, the quality of the result depends on how you label the data.

If your data is properly labeled, it results in good quality output, while improperly labeled data results in bad output. While labeling data, there are pitfalls to avoid to produce a good-quality result.

For example, if we are to build a model using Kili Technology, and we are to draw a bounding box around every pedestrian in a traffic, the following can go wrong:

**1. Misinterpretation of instruction:** Instead of drawing a bounding box around a pedestrian, the annotator may draw it around multiple pedestrians.
**2. Occlusion Error:** Instead of annotating only the visible part of a pedestrian, the annotator may place a bounding box around the expected size of a pedestrian.
**3. Missing a label:** The annotator may fail to place a label around one or more pedestrians.
**4. Unfit labeling:** The bounding box may not properly fit a pedestrian.
**5. Classification error:** Every data model are designed to be useful in the multiple-case scenario, but if your data sample is imbalanced, like presenting a drawn image of pedestrians in a circle, instead of a real-life situation, then the result may only be able to identify pedestrians in a drawn image.
**6. Annotator bias:** An annotator may be biased in labeling if he doesn't have a good knowledge of the data or if he has a different opinion, this can result in an ineffective result.
**7. Recession in data accuracy:** Data is constantly evolving, hence a model on old data may become ineffective to identify similar data in the present if there have been some changes to the scenario.

For each point, I am also going to include ways in which such errors can be avoided.

I will also include a second case scenario and analyze what may go wrong and how to avoid such errors.

**Comment by theodu** [comment]
Hi @Renerd-max 
Nice outline! the occlusion Error is very specific to image annotation. If you can also include some text issues that would be wonderful!
Also, I think that something that is very important to mention is the fact that misunderstandings or mistakes in an annotation can lead to the need to re annotate all data. If something went wrong and is seen too late, it could cost many many hours of data annotation. This explains why it is a very important subject.
A bad upstream definition of the project annotation and weak supervision to spot mistakes can have a huge cost. I provide you with a good reference on how to properly manage an annotation project to avoid mistakes you might talk about in your article: https://assets.bbhub.io/company/sites/40/2020/09/Annotation-Best-Practices-091020-FINAL.pdf

I assign you to it. 
Thank you and Happy New Year!

**Comment by Renerd-max** [comment]
Hi @theodu I am done with this and it is now available for review, here is the link to the google doc:
https://docs.google.com/document/d/16HxktnoYUF92NDrCxQHnyiFAsjsD1z6Cy4IrEVqJ6NQ/edit?usp=drivesdk

And here is the link to the Google slide image: 
https://docs.google.com/presentation/d/11Xx94fPSH7KpH8MFegIA7RHMnGLoOh4-l7I4e_rQCWU/edit?usp=drivesdk

There was an instruction stating we are to download and fill the article guideline, but I do not have access to this guideline, nor do I know how to submit it, kindly put me through it.

**Comment by theodu** [comment]
Hi @Renerd-max 
Great! I answered your questions by mail.
We will review this article ASAP.

**Comment by Renerd-max** [comment]
Hi, @theodu the link has been updated.

https://docs.google.com/document/d/14jqdpTRKTchMq4IbvHx32YeheZ_e-VzVGlFBmEM85yU/edit?usp=drivesdk

**Comment by Renerd-max** [comment]
Hi, @theodu you can now review this topic since I have made the necessary changes.

https://docs.google.com/document/d/14jqdpTRKTchMq4IbvHx32YeheZ_e-VzVGlFBmEM85yU/edit?usp=drivesdk

**Comment by theodu** [comment]
Hi @Renerd-max 
Thank you! Thank you for having taken the comment, the targeted user is now more in line with our objectives!
The article looks good, I just added one more comment to have cleaner images.

**Comment by theodu** [comment]
hi, @Renerd-max I validate this article!
You can now follow the FAQ to send us your invoice. We keep you in touch of when we will publish this article ;)

**Comment by Renerd-max** [comment]
@theodu according to the faq, the article must be published before I submit an invoice, therefore, I must wait for this article to be published, right?

**Comment by theodu** [comment]
Yes indeed, lets do it that way ;)

**Comment by theodu** [comment]
@Renerd-max, the last update is needed for the article before being ready to be published.
in fact, we noticed that it lacks illustration. they are pictures for the image case but none for the text case. can you please add images for the text case please?

**Comment by Renerd-max** [comment]
Hi @theodu this article has now been updated with an illustration for the text case

**Comment by theodu** [comment]
hi @Renerd-max I don't see them, is the last link that you put in the comment the updated one ?

**Comment by Renerd-max** [comment]
@theodu here is the link.

https://docs.google.com/document/d/1zNCFmGJx-4wjwH0pUzMPcqCkzv36QWGpN3IG7FYiW50/edit?usp=drivesdk

I added illustrations to the first point under text, the rest don't necessarily need one since they are theoretical or self-explanatory.

**Comment by theodu** [comment]
The two graphics are stretched and they don't add a lot of value. I think that you can get rid of them. Rather try to add another image for the other text part.

**Comment by Renerd-max** [comment]
I did that already

**Comment by Renerd-max** [comment]
@theodu the article has been updated

**Comment by theodu** [comment]
Hi @Renerd-max 
I revalidate your article, it will be published next week

**Comment by Renerd-max** [comment]
Alright @theodu I should apply the experience here to the next one

**Comment by theodu** [comment]
Hi @Renerd-max 
I sent you an invitation by mail to join us as a blog member on WordPress platform.
When you accept it, you can create a new post and get your article in shape.

**Comment by Renerd-max** [comment]
Invitation accepted, I shall do so at my earliest convenience.

Renerd

**Comment by Renerd-max** [comment]
Submitted for review

**Comment by theodu** [comment]
Hello Renerd, 
your article is planned to be published tomorrow at 9:00 CET.
I just changed one image to make it more professional.
You will be able to submit your invoice tomorrow with the link
